#!/bin/bash

# Configure Coordinator for Hub Chain
#
# This script creates the coordinator config file from scratch with Hub Chain addresses.
# Coordinator has NO crypto keys - it only monitors events and handles negotiation.

set -e

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"
source "$SCRIPT_DIR/../util_mvm.sh"

# Setup project root and logging
setup_project_root
setup_logging "configure-coordinator-hub"
cd "$PROJECT_ROOT"

log_and_echo "   Configuring coordinator for Hub Chain..."
log_and_echo ""

# Extract deployed address from aptos profile
HUB_MODULE_ADDR=$(get_profile_address "intent-account-chain1")

if [ -z "$HUB_MODULE_ADDR" ]; then
    log_and_echo "   ERROR: Could not extract Hub module address"
    exit 1
fi

log_and_echo "   Hub module: $HUB_MODULE_ADDR"

# Create config file path
COORDINATOR_E2E_CI_TESTING_CONFIG="$PROJECT_ROOT/coordinator/config/coordinator-e2e-ci-testing.toml"

# Create config directory if needed
mkdir -p "$(dirname "$COORDINATOR_E2E_CI_TESTING_CONFIG")"

# Generate the complete config file from scratch
cat > "$COORDINATOR_E2E_CI_TESTING_CONFIG" << EOF
# Coordinator E2E Testing Configuration
# Auto-generated by configure-coordinator.sh - DO NOT EDIT MANUALLY
# NOTE: Coordinator has NO crypto keys - it only monitors and handles negotiation

[hub_chain]
name = "Hub Chain"
rpc_url = "http://127.0.0.1:8080"
chain_id = 1
intent_module_addr = "0x$HUB_MODULE_ADDR"

[coordinator]
polling_interval_ms = 2000
validation_timeout_ms = 30000

[api]
host = "127.0.0.1"
port = 3333
cors_origins = ["http://localhost:3333"]
EOF

export COORDINATOR_CONFIG_PATH="$COORDINATOR_E2E_CI_TESTING_CONFIG"

log_and_echo "   Created coordinator-e2e-ci-testing.toml with Hub Chain addresses"
log_and_echo ""
