#!/bin/bash

# Configure Trusted-GMP for Hub Chain
#
# This script creates the trusted-gmp config file from scratch with Hub Chain addresses.
# Trusted-GMP has crypto keys for validation and signing.

set -e

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"
source "$SCRIPT_DIR/../util_mvm.sh"

# Setup project root and logging
setup_project_root
setup_logging "configure-trusted-gmp-hub"
cd "$PROJECT_ROOT"

log_and_echo "   Configuring trusted-gmp for Hub Chain..."
log_and_echo ""

# Extract deployed address from aptos profile
HUB_MODULE_ADDR=$(get_profile_address "intent-account-chain1")

if [ -z "$HUB_MODULE_ADDR" ]; then
    log_and_echo "   ERROR: Could not extract Hub module address"
    exit 1
fi

log_and_echo "   Hub module: $HUB_MODULE_ADDR"

# Generate fresh ephemeral keys for trusted-gmp
generate_trusted_gmp_keys

# Create config file path
TRUSTED_GMP_E2E_CI_TESTING_CONFIG="$PROJECT_ROOT/trusted-gmp/config/trusted-gmp-e2e-ci-testing.toml"

# Create config directory if needed
mkdir -p "$(dirname "$TRUSTED_GMP_E2E_CI_TESTING_CONFIG")"

# Generate the complete config file from scratch
cat > "$TRUSTED_GMP_E2E_CI_TESTING_CONFIG" << EOF
# Trusted-GMP E2E Testing Configuration
# Auto-generated by configure-trusted-gmp.sh - DO NOT EDIT MANUALLY

[hub_chain]
name = "Hub Chain"
rpc_url = "http://127.0.0.1:8080"
chain_id = 1
intent_module_addr = "0x$HUB_MODULE_ADDR"

[trusted_gmp]
private_key_env = "E2E_TRUSTED_GMP_PRIVATE_KEY"
public_key_env = "E2E_TRUSTED_GMP_PUBLIC_KEY"
polling_interval_ms = 2000
validation_timeout_ms = 30000

[api]
host = "127.0.0.1"
port = 3334
cors_origins = ["http://localhost:3334"]
EOF

export TRUSTED_GMP_CONFIG_PATH="$TRUSTED_GMP_E2E_CI_TESTING_CONFIG"

log_and_echo "   Created trusted-gmp-e2e-ci-testing.toml with Hub Chain addresses"
log_and_echo ""
