#!/bin/bash

# Run Coordinator Rust Integration Tests
#
# This script runs the Rust integration tests for the coordinator service.
# It creates a temporary test entry point and runs cargo test.

set -e

# Source common utilities
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/../util.sh"

# Setup project root and logging
setup_project_root
setup_logging "coordinator-rust-integration-tests"
cd "$PROJECT_ROOT"

# Ensure coordinator config path matches the E2E config generated by configure-coordinator scripts
COORDINATOR_CONFIG_PATH="$PROJECT_ROOT/coordinator/config/coordinator-e2e-ci-testing.toml"
if [ ! -f "$COORDINATOR_CONFIG_PATH" ]; then
    log_and_echo "❌ PANIC: Coordinator config not found at $COORDINATOR_CONFIG_PATH"
    log_and_echo "   Make sure chain-hub/configure-coordinator.sh and chain-connected-mvm/configure-coordinator.sh have run."
    exit 1
fi
export COORDINATOR_CONFIG_PATH

# Load trusted-gmp keys (generated during deployment)
load_trusted_gmp_keys


# Create a temporary integration test entry point
INTEGRATION_TEST_FILE="coordinator/tests/integration_test_e2e.rs"
cat > "$INTEGRATION_TEST_FILE" << 'EOF'
//! E2E Integration tests entry point
//!
//! This file is temporarily generated by coordinator-rust-integration-tests.sh to load e2e tests.

#[path = "../../testing-infra/ci-e2e/e2e-tests-mvm/coordinator-rust-integration-tests/mod.rs"]
mod integration;
EOF

# Run the tests from coordinator directory
cd coordinator
cargo test --test integration_test_e2e

# Clean up temporary test file
cd "$PROJECT_ROOT"
rm -f "$INTEGRATION_TEST_FILE"


